/*
GitLab API

An OpenAPI definition for the GitLab REST API.
Few API resources or endpoints are currently included.
The intent is to expand this to match the entire Markdown documentation of the API:
<https://docs.gitlab.com/ee/api/>. Contributions are welcome.

When viewing this on gitlab.com, you can test API calls directly from the browser
against the `gitlab.com` instance, if you are logged in.
The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie),
so each request is made using your account.

Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html)


The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * API_Entities_MetricImage model
 * @export
 * @interface APIEntitiesMetricImage
 */
export interface APIEntitiesMetricImage {
    /**
     * 
     * @type {number}
     * @memberof APIEntitiesMetricImage
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof APIEntitiesMetricImage
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof APIEntitiesMetricImage
     */
    'filename'?: string;
    /**
     * 
     * @type {string}
     * @memberof APIEntitiesMetricImage
     */
    'file_path'?: string;
    /**
     * 
     * @type {string}
     * @memberof APIEntitiesMetricImage
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof APIEntitiesMetricImage
     */
    'url_text'?: string;
}

