/*
GitLab API

An OpenAPI definition for the GitLab REST API.
Few API resources or endpoints are currently included.
The intent is to expand this to match the entire Markdown documentation of the API:
<https://docs.gitlab.com/ee/api/>. Contributions are welcome.

When viewing this on gitlab.com, you can test API calls directly from the browser
against the `gitlab.com` instance, if you are logged in.
The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie),
so each request is made using your account.

Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html)


The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApplicationsCreateNewApplicationRequest
 */
export interface ApplicationsCreateNewApplicationRequest {
    /**
     * Name of the application.
     * @type {string}
     * @memberof ApplicationsCreateNewApplicationRequest
     */
    'name': string;
    /**
     * Redirect URI of the application.
     * @type {string}
     * @memberof ApplicationsCreateNewApplicationRequest
     */
    'redirect_uri': string;
    /**
     * Scopes of the application. You can specify multiple scopes by separating\\                                  each scope using a space
     * @type {string}
     * @memberof ApplicationsCreateNewApplicationRequest
     */
    'scopes': string;
    /**
     * The application is used where the client secret can be kept confidential. Native mobile apps \\                         and Single Page Apps are considered non-confidential. Defaults to true if not supplied
     * @type {boolean}
     * @memberof ApplicationsCreateNewApplicationRequest
     */
    'confidential'?: boolean;
}

