/*
GitLab API

An OpenAPI definition for the GitLab REST API.
Few API resources or endpoints are currently included.
The intent is to expand this to match the entire Markdown documentation of the API:
<https://docs.gitlab.com/ee/api/>. Contributions are welcome.

When viewing this on gitlab.com, you can test API calls directly from the browser
against the `gitlab.com` instance, if you are logged in.
The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie),
so each request is made using your account.

Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html)


The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApplicationModifyAppearanceRequest
 */
export interface ApplicationModifyAppearanceRequest {
    /**
     * Instance title on the sign in / sign up page
     * @type {string}
     * @memberof ApplicationModifyAppearanceRequest
     */
    'title'?: string;
    /**
     * Markdown text shown on the sign in / sign up page
     * @type {string}
     * @memberof ApplicationModifyAppearanceRequest
     */
    'description'?: string;
    /**
     * Name of the Progressive Web App
     * @type {string}
     * @memberof ApplicationModifyAppearanceRequest
     */
    'pwa_name'?: string;
    /**
     * Optional, short name for Progressive Web App
     * @type {string}
     * @memberof ApplicationModifyAppearanceRequest
     */
    'pwa_short_name'?: string;
    /**
     * An explanation of what the Progressive Web App does
     * @type {string}
     * @memberof ApplicationModifyAppearanceRequest
     */
    'pwa_description'?: string;
    /**
     * Instance image used on the sign in / sign up page
     * @type {Uint8Array | File | buffer.File}
     * @memberof ApplicationModifyAppearanceRequest
     */
    'logo'?: Uint8Array | File | buffer.File;
    /**
     * Icon used for Progressive Web App
     * @type {Uint8Array | File | buffer.File}
     * @memberof ApplicationModifyAppearanceRequest
     */
    'pwa_icon'?: Uint8Array | File | buffer.File;
    /**
     * Instance image used for the main navigation bar
     * @type {Uint8Array | File | buffer.File}
     * @memberof ApplicationModifyAppearanceRequest
     */
    'header_logo'?: Uint8Array | File | buffer.File;
    /**
     * Instance favicon in .ico/.png format
     * @type {Uint8Array | File | buffer.File}
     * @memberof ApplicationModifyAppearanceRequest
     */
    'favicon'?: Uint8Array | File | buffer.File;
    /**
     * Markdown text shown on the new project page
     * @type {string}
     * @memberof ApplicationModifyAppearanceRequest
     */
    'new_project_guidelines'?: string;
    /**
     * Markdown text shown on the profile page below Public Avatar
     * @type {string}
     * @memberof ApplicationModifyAppearanceRequest
     */
    'profile_image_guidelines'?: string;
    /**
     * Message within the system header bar
     * @type {string}
     * @memberof ApplicationModifyAppearanceRequest
     */
    'header_message'?: string;
    /**
     * Message within the system footer bar
     * @type {string}
     * @memberof ApplicationModifyAppearanceRequest
     */
    'footer_message'?: string;
    /**
     * Background color for the system header / footer bar
     * @type {string}
     * @memberof ApplicationModifyAppearanceRequest
     */
    'message_background_color'?: string;
    /**
     * Font color for the system header / footer bar
     * @type {string}
     * @memberof ApplicationModifyAppearanceRequest
     */
    'message_font_color'?: string;
    /**
     * Add header and footer to all outgoing emails if enabled
     * @type {boolean}
     * @memberof ApplicationModifyAppearanceRequest
     */
    'email_header_and_footer_enabled'?: boolean;
}

