/*
GitLab API

An OpenAPI definition for the GitLab REST API.
Few API resources or endpoints are currently included.
The intent is to expand this to match the entire Markdown documentation of the API:
<https://docs.gitlab.com/ee/api/>. Contributions are welcome.

When viewing this on gitlab.com, you can test API calls directly from the browser
against the `gitlab.com` instance, if you are logged in.
The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie),
so each request is made using your account.

Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html)


The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BroadcastmessagesUpdateMessageRequest
 */
export interface BroadcastmessagesUpdateMessageRequest {
    /**
     * Message to display
     * @type {string}
     * @memberof BroadcastmessagesUpdateMessageRequest
     */
    'message'?: string;
    /**
     * Starting time
     * @type {string}
     * @memberof BroadcastmessagesUpdateMessageRequest
     */
    'starts_at'?: string;
    /**
     * Ending time
     * @type {string}
     * @memberof BroadcastmessagesUpdateMessageRequest
     */
    'ends_at'?: string;
    /**
     * Background color
     * @type {string}
     * @memberof BroadcastmessagesUpdateMessageRequest
     */
    'color'?: string;
    /**
     * Foreground color
     * @type {string}
     * @memberof BroadcastmessagesUpdateMessageRequest
     */
    'font'?: string;
    /**
     * Target user roles
     * @type {Array<number>}
     * @memberof BroadcastmessagesUpdateMessageRequest
     */
    'target_access_levels'?: Array<BroadcastmessagesUpdateMessageRequestTargetAccessLevelsEnum>;
    /**
     * Target path
     * @type {string}
     * @memberof BroadcastmessagesUpdateMessageRequest
     */
    'target_path'?: string;
    /**
     * Broadcast Type
     * @type {string}
     * @memberof BroadcastmessagesUpdateMessageRequest
     */
    'broadcast_type'?: BroadcastmessagesUpdateMessageRequestBroadcastTypeEnum;
    /**
     * Is dismissable
     * @type {boolean}
     * @memberof BroadcastmessagesUpdateMessageRequest
     */
    'dismissable'?: boolean;
}

type BroadcastmessagesUpdateMessageRequestTargetAccessLevelsEnum = 10 | 20 | 30 | 40 | 50
type BroadcastmessagesUpdateMessageRequestBroadcastTypeEnum = 'banner' | 'notification'


