/*
GitLab API

An OpenAPI definition for the GitLab REST API.
Few API resources or endpoints are currently included.
The intent is to expand this to match the entire Markdown documentation of the API:
<https://docs.gitlab.com/ee/api/>. Contributions are welcome.

When viewing this on gitlab.com, you can test API calls directly from the browser
against the `gitlab.com` instance, if you are logged in.
The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie),
so each request is made using your account.

Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html)


The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BroadcastmessagesCreateMessageRequest
 */
export interface BroadcastmessagesCreateMessageRequest {
    /**
     * Message to display
     * @type {string}
     * @memberof BroadcastmessagesCreateMessageRequest
     */
    'message': string;
    /**
     * Starting time
     * @type {string}
     * @memberof BroadcastmessagesCreateMessageRequest
     */
    'starts_at'?: string;
    /**
     * Ending time
     * @type {string}
     * @memberof BroadcastmessagesCreateMessageRequest
     */
    'ends_at'?: string;
    /**
     * Background color
     * @type {string}
     * @memberof BroadcastmessagesCreateMessageRequest
     */
    'color'?: string;
    /**
     * Foreground color
     * @type {string}
     * @memberof BroadcastmessagesCreateMessageRequest
     */
    'font'?: string;
    /**
     * Target user roles
     * @type {Array<number>}
     * @memberof BroadcastmessagesCreateMessageRequest
     */
    'target_access_levels'?: Array<BroadcastmessagesCreateMessageRequestTargetAccessLevelsEnum>;
    /**
     * Target path
     * @type {string}
     * @memberof BroadcastmessagesCreateMessageRequest
     */
    'target_path'?: string;
    /**
     * Broadcast type. Defaults to banner
     * @type {string}
     * @memberof BroadcastmessagesCreateMessageRequest
     */
    'broadcast_type'?: BroadcastmessagesCreateMessageRequestBroadcastTypeEnum;
    /**
     * Is dismissable
     * @type {boolean}
     * @memberof BroadcastmessagesCreateMessageRequest
     */
    'dismissable'?: boolean;
}

type BroadcastmessagesCreateMessageRequestTargetAccessLevelsEnum = 10 | 20 | 30 | 40 | 50
type BroadcastmessagesCreateMessageRequestBroadcastTypeEnum = 'banner' | 'notification'


