/*
GitLab API

An OpenAPI definition for the GitLab REST API.
Few API resources or endpoints are currently included.
The intent is to expand this to match the entire Markdown documentation of the API:
<https://docs.gitlab.com/ee/api/>. Contributions are welcome.

When viewing this on gitlab.com, you can test API calls directly from the browser
against the `gitlab.com` instance, if you are logged in.
The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie),
so each request is made using your account.

Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html)


The version of the OpenAPI document: v4


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BulkimportsStartNewMigrationRequest
 */
export interface BulkimportsStartNewMigrationRequest {
    /**
     * Source GitLab instance URL
     * @type {string}
     * @memberof BulkimportsStartNewMigrationRequest
     */
    'configuration[url]': string;
    /**
     * Access token to the source GitLab instance
     * @type {string}
     * @memberof BulkimportsStartNewMigrationRequest
     */
    'configuration[access_token]': string;
    /**
     * Source entity type
     * @type {Array<string>}
     * @memberof BulkimportsStartNewMigrationRequest
     */
    'entities[source_type]': Array<BulkimportsStartNewMigrationRequestEntitiesSourceTypeEnum>;
    /**
     * Relative path of the source entity to import
     * @type {Array<string>}
     * @memberof BulkimportsStartNewMigrationRequest
     */
    'entities[source_full_path]': Array<string>;
    /**
     * Destination namespace for the entity
     * @type {Array<string>}
     * @memberof BulkimportsStartNewMigrationRequest
     */
    'entities[destination_namespace]': Array<string>;
    /**
     * Destination slug for the entity
     * @type {Array<string>}
     * @memberof BulkimportsStartNewMigrationRequest
     */
    'entities[destination_slug]'?: Array<string>;
    /**
     * Deprecated: Use :destination_slug instead. Destination slug for the entity
     * @type {Array<string>}
     * @memberof BulkimportsStartNewMigrationRequest
     */
    'entities[destination_name]'?: Array<string>;
    /**
     * Indicates group migration should include nested projects
     * @type {Array<boolean>}
     * @memberof BulkimportsStartNewMigrationRequest
     */
    'entities[migrate_projects]'?: Array<boolean>;
}

type BulkimportsStartNewMigrationRequestEntitiesSourceTypeEnum = 'group_entity' | 'project_entity'


